// Generated by gencpp from file mh_hazard/CLIPRequest.msg
// DO NOT EDIT!


#ifndef MH_HAZARD_MESSAGE_CLIPREQUEST_H
#define MH_HAZARD_MESSAGE_CLIPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace mh_hazard
{
template <class ContainerAllocator>
struct CLIPRequest_
{
  typedef CLIPRequest_<ContainerAllocator> Type;

  CLIPRequest_()
    : images()
    , text()  {
    }
  CLIPRequest_(const ContainerAllocator& _alloc)
    : images(_alloc)
    , text(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::sensor_msgs::Image_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::sensor_msgs::Image_<ContainerAllocator> >> _images_type;
  _images_type images;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _text_type;
  _text_type text;





  typedef boost::shared_ptr< ::mh_hazard::CLIPRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mh_hazard::CLIPRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CLIPRequest_

typedef ::mh_hazard::CLIPRequest_<std::allocator<void> > CLIPRequest;

typedef boost::shared_ptr< ::mh_hazard::CLIPRequest > CLIPRequestPtr;
typedef boost::shared_ptr< ::mh_hazard::CLIPRequest const> CLIPRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mh_hazard::CLIPRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mh_hazard::CLIPRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mh_hazard::CLIPRequest_<ContainerAllocator1> & lhs, const ::mh_hazard::CLIPRequest_<ContainerAllocator2> & rhs)
{
  return lhs.images == rhs.images &&
    lhs.text == rhs.text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mh_hazard::CLIPRequest_<ContainerAllocator1> & lhs, const ::mh_hazard::CLIPRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mh_hazard

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mh_hazard::CLIPRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mh_hazard::CLIPRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mh_hazard::CLIPRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mh_hazard::CLIPRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mh_hazard::CLIPRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mh_hazard::CLIPRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mh_hazard::CLIPRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "425dd409481b97841948e5ddfafde695";
  }

  static const char* value(const ::mh_hazard::CLIPRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x425dd409481b9784ULL;
  static const uint64_t static_value2 = 0x1948e5ddfafde695ULL;
};

template<class ContainerAllocator>
struct DataType< ::mh_hazard::CLIPRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mh_hazard/CLIPRequest";
  }

  static const char* value(const ::mh_hazard::CLIPRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mh_hazard::CLIPRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image[] images\n"
"string[] text\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mh_hazard::CLIPRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mh_hazard::CLIPRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.images);
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CLIPRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mh_hazard::CLIPRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mh_hazard::CLIPRequest_<ContainerAllocator>& v)
  {
    s << indent << "images[]" << std::endl;
    for (size_t i = 0; i < v.images.size(); ++i)
    {
      s << indent << "  images[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "    ", v.images[i]);
    }
    s << indent << "text[]" << std::endl;
    for (size_t i = 0; i < v.text.size(); ++i)
    {
      s << indent << "  text[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.text[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MH_HAZARD_MESSAGE_CLIPREQUEST_H
