// Generated by gencpp from file mh_hazard/DetectSlot.msg
// DO NOT EDIT!


#ifndef MH_HAZARD_MESSAGE_DETECTSLOT_H
#define MH_HAZARD_MESSAGE_DETECTSLOT_H

#include <ros/service_traits.h>


#include <mh_hazard/DetectSlotRequest.h>
#include <mh_hazard/DetectSlotResponse.h>


namespace mh_hazard
{

struct DetectSlot
{

typedef DetectSlotRequest Request;
typedef DetectSlotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetectSlot
} // namespace mh_hazard


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mh_hazard::DetectSlot > {
  static const char* value()
  {
    return "8f4fa51b6ae999cb5417077cdbe136e8";
  }

  static const char* value(const ::mh_hazard::DetectSlot&) { return value(); }
};

template<>
struct DataType< ::mh_hazard::DetectSlot > {
  static const char* value()
  {
    return "mh_hazard/DetectSlot";
  }

  static const char* value(const ::mh_hazard::DetectSlot&) { return value(); }
};


// service_traits::MD5Sum< ::mh_hazard::DetectSlotRequest> should match
// service_traits::MD5Sum< ::mh_hazard::DetectSlot >
template<>
struct MD5Sum< ::mh_hazard::DetectSlotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mh_hazard::DetectSlot >::value();
  }
  static const char* value(const ::mh_hazard::DetectSlotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mh_hazard::DetectSlotRequest> should match
// service_traits::DataType< ::mh_hazard::DetectSlot >
template<>
struct DataType< ::mh_hazard::DetectSlotRequest>
{
  static const char* value()
  {
    return DataType< ::mh_hazard::DetectSlot >::value();
  }
  static const char* value(const ::mh_hazard::DetectSlotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mh_hazard::DetectSlotResponse> should match
// service_traits::MD5Sum< ::mh_hazard::DetectSlot >
template<>
struct MD5Sum< ::mh_hazard::DetectSlotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mh_hazard::DetectSlot >::value();
  }
  static const char* value(const ::mh_hazard::DetectSlotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mh_hazard::DetectSlotResponse> should match
// service_traits::DataType< ::mh_hazard::DetectSlot >
template<>
struct DataType< ::mh_hazard::DetectSlotResponse>
{
  static const char* value()
  {
    return DataType< ::mh_hazard::DetectSlot >::value();
  }
  static const char* value(const ::mh_hazard::DetectSlotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MH_HAZARD_MESSAGE_DETECTSLOT_H
