// Generated by gencpp from file mh_hazard/Indicate.msg
// DO NOT EDIT!


#ifndef MH_HAZARD_MESSAGE_INDICATE_H
#define MH_HAZARD_MESSAGE_INDICATE_H

#include <ros/service_traits.h>


#include <mh_hazard/IndicateRequest.h>
#include <mh_hazard/IndicateResponse.h>


namespace mh_hazard
{

struct Indicate
{

typedef IndicateRequest Request;
typedef IndicateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Indicate
} // namespace mh_hazard


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mh_hazard::Indicate > {
  static const char* value()
  {
    return "1091700a12e6e9539ab6bad6f0ed20bf";
  }

  static const char* value(const ::mh_hazard::Indicate&) { return value(); }
};

template<>
struct DataType< ::mh_hazard::Indicate > {
  static const char* value()
  {
    return "mh_hazard/Indicate";
  }

  static const char* value(const ::mh_hazard::Indicate&) { return value(); }
};


// service_traits::MD5Sum< ::mh_hazard::IndicateRequest> should match
// service_traits::MD5Sum< ::mh_hazard::Indicate >
template<>
struct MD5Sum< ::mh_hazard::IndicateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mh_hazard::Indicate >::value();
  }
  static const char* value(const ::mh_hazard::IndicateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mh_hazard::IndicateRequest> should match
// service_traits::DataType< ::mh_hazard::Indicate >
template<>
struct DataType< ::mh_hazard::IndicateRequest>
{
  static const char* value()
  {
    return DataType< ::mh_hazard::Indicate >::value();
  }
  static const char* value(const ::mh_hazard::IndicateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mh_hazard::IndicateResponse> should match
// service_traits::MD5Sum< ::mh_hazard::Indicate >
template<>
struct MD5Sum< ::mh_hazard::IndicateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mh_hazard::Indicate >::value();
  }
  static const char* value(const ::mh_hazard::IndicateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mh_hazard::IndicateResponse> should match
// service_traits::DataType< ::mh_hazard::Indicate >
template<>
struct DataType< ::mh_hazard::IndicateResponse>
{
  static const char* value()
  {
    return DataType< ::mh_hazard::Indicate >::value();
  }
  static const char* value(const ::mh_hazard::IndicateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MH_HAZARD_MESSAGE_INDICATE_H
