// Generated by gencpp from file mh_hazard/LLMImage.msg
// DO NOT EDIT!


#ifndef MH_HAZARD_MESSAGE_LLMIMAGE_H
#define MH_HAZARD_MESSAGE_LLMIMAGE_H

#include <ros/service_traits.h>


#include <mh_hazard/LLMImageRequest.h>
#include <mh_hazard/LLMImageResponse.h>


namespace mh_hazard
{

struct LLMImage
{

typedef LLMImageRequest Request;
typedef LLMImageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LLMImage
} // namespace mh_hazard


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mh_hazard::LLMImage > {
  static const char* value()
  {
    return "9a1bc7ba89df6c5148b89de056b79bbb";
  }

  static const char* value(const ::mh_hazard::LLMImage&) { return value(); }
};

template<>
struct DataType< ::mh_hazard::LLMImage > {
  static const char* value()
  {
    return "mh_hazard/LLMImage";
  }

  static const char* value(const ::mh_hazard::LLMImage&) { return value(); }
};


// service_traits::MD5Sum< ::mh_hazard::LLMImageRequest> should match
// service_traits::MD5Sum< ::mh_hazard::LLMImage >
template<>
struct MD5Sum< ::mh_hazard::LLMImageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mh_hazard::LLMImage >::value();
  }
  static const char* value(const ::mh_hazard::LLMImageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mh_hazard::LLMImageRequest> should match
// service_traits::DataType< ::mh_hazard::LLMImage >
template<>
struct DataType< ::mh_hazard::LLMImageRequest>
{
  static const char* value()
  {
    return DataType< ::mh_hazard::LLMImage >::value();
  }
  static const char* value(const ::mh_hazard::LLMImageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mh_hazard::LLMImageResponse> should match
// service_traits::MD5Sum< ::mh_hazard::LLMImage >
template<>
struct MD5Sum< ::mh_hazard::LLMImageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mh_hazard::LLMImage >::value();
  }
  static const char* value(const ::mh_hazard::LLMImageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mh_hazard::LLMImageResponse> should match
// service_traits::DataType< ::mh_hazard::LLMImage >
template<>
struct DataType< ::mh_hazard::LLMImageResponse>
{
  static const char* value()
  {
    return DataType< ::mh_hazard::LLMImage >::value();
  }
  static const char* value(const ::mh_hazard::LLMImageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MH_HAZARD_MESSAGE_LLMIMAGE_H
