// Generated by gencpp from file mh_hazard/MoveITNamedPose.msg
// DO NOT EDIT!


#ifndef MH_HAZARD_MESSAGE_MOVEITNAMEDPOSE_H
#define MH_HAZARD_MESSAGE_MOVEITNAMEDPOSE_H

#include <ros/service_traits.h>


#include <mh_hazard/MoveITNamedPoseRequest.h>
#include <mh_hazard/MoveITNamedPoseResponse.h>


namespace mh_hazard
{

struct MoveITNamedPose
{

typedef MoveITNamedPoseRequest Request;
typedef MoveITNamedPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveITNamedPose
} // namespace mh_hazard


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mh_hazard::MoveITNamedPose > {
  static const char* value()
  {
    return "4472470b43f5627ee4d8a019759b7942";
  }

  static const char* value(const ::mh_hazard::MoveITNamedPose&) { return value(); }
};

template<>
struct DataType< ::mh_hazard::MoveITNamedPose > {
  static const char* value()
  {
    return "mh_hazard/MoveITNamedPose";
  }

  static const char* value(const ::mh_hazard::MoveITNamedPose&) { return value(); }
};


// service_traits::MD5Sum< ::mh_hazard::MoveITNamedPoseRequest> should match
// service_traits::MD5Sum< ::mh_hazard::MoveITNamedPose >
template<>
struct MD5Sum< ::mh_hazard::MoveITNamedPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mh_hazard::MoveITNamedPose >::value();
  }
  static const char* value(const ::mh_hazard::MoveITNamedPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mh_hazard::MoveITNamedPoseRequest> should match
// service_traits::DataType< ::mh_hazard::MoveITNamedPose >
template<>
struct DataType< ::mh_hazard::MoveITNamedPoseRequest>
{
  static const char* value()
  {
    return DataType< ::mh_hazard::MoveITNamedPose >::value();
  }
  static const char* value(const ::mh_hazard::MoveITNamedPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mh_hazard::MoveITNamedPoseResponse> should match
// service_traits::MD5Sum< ::mh_hazard::MoveITNamedPose >
template<>
struct MD5Sum< ::mh_hazard::MoveITNamedPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mh_hazard::MoveITNamedPose >::value();
  }
  static const char* value(const ::mh_hazard::MoveITNamedPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mh_hazard::MoveITNamedPoseResponse> should match
// service_traits::DataType< ::mh_hazard::MoveITNamedPose >
template<>
struct DataType< ::mh_hazard::MoveITNamedPoseResponse>
{
  static const char* value()
  {
    return DataType< ::mh_hazard::MoveITNamedPose >::value();
  }
  static const char* value(const ::mh_hazard::MoveITNamedPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MH_HAZARD_MESSAGE_MOVEITNAMEDPOSE_H
