// Generated by gencpp from file mh_hazard/MoveITPose.msg
// DO NOT EDIT!


#ifndef MH_HAZARD_MESSAGE_MOVEITPOSE_H
#define MH_HAZARD_MESSAGE_MOVEITPOSE_H

#include <ros/service_traits.h>


#include <mh_hazard/MoveITPoseRequest.h>
#include <mh_hazard/MoveITPoseResponse.h>


namespace mh_hazard
{

struct MoveITPose
{

typedef MoveITPoseRequest Request;
typedef MoveITPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveITPose
} // namespace mh_hazard


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mh_hazard::MoveITPose > {
  static const char* value()
  {
    return "1d4e3f01f751b136dce2bc699f1d7748";
  }

  static const char* value(const ::mh_hazard::MoveITPose&) { return value(); }
};

template<>
struct DataType< ::mh_hazard::MoveITPose > {
  static const char* value()
  {
    return "mh_hazard/MoveITPose";
  }

  static const char* value(const ::mh_hazard::MoveITPose&) { return value(); }
};


// service_traits::MD5Sum< ::mh_hazard::MoveITPoseRequest> should match
// service_traits::MD5Sum< ::mh_hazard::MoveITPose >
template<>
struct MD5Sum< ::mh_hazard::MoveITPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mh_hazard::MoveITPose >::value();
  }
  static const char* value(const ::mh_hazard::MoveITPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mh_hazard::MoveITPoseRequest> should match
// service_traits::DataType< ::mh_hazard::MoveITPose >
template<>
struct DataType< ::mh_hazard::MoveITPoseRequest>
{
  static const char* value()
  {
    return DataType< ::mh_hazard::MoveITPose >::value();
  }
  static const char* value(const ::mh_hazard::MoveITPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mh_hazard::MoveITPoseResponse> should match
// service_traits::MD5Sum< ::mh_hazard::MoveITPose >
template<>
struct MD5Sum< ::mh_hazard::MoveITPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mh_hazard::MoveITPose >::value();
  }
  static const char* value(const ::mh_hazard::MoveITPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mh_hazard::MoveITPoseResponse> should match
// service_traits::DataType< ::mh_hazard::MoveITPose >
template<>
struct DataType< ::mh_hazard::MoveITPoseResponse>
{
  static const char* value()
  {
    return DataType< ::mh_hazard::MoveITPose >::value();
  }
  static const char* value(const ::mh_hazard::MoveITPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MH_HAZARD_MESSAGE_MOVEITPOSE_H
