// Generated by gencpp from file mh_hazard/OrientCamera.msg
// DO NOT EDIT!


#ifndef MH_HAZARD_MESSAGE_ORIENTCAMERA_H
#define MH_HAZARD_MESSAGE_ORIENTCAMERA_H

#include <ros/service_traits.h>


#include <mh_hazard/OrientCameraRequest.h>
#include <mh_hazard/OrientCameraResponse.h>


namespace mh_hazard
{

struct OrientCamera
{

typedef OrientCameraRequest Request;
typedef OrientCameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OrientCamera
} // namespace mh_hazard


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mh_hazard::OrientCamera > {
  static const char* value()
  {
    return "af7bedf12e890f6394e93b01ad2de69e";
  }

  static const char* value(const ::mh_hazard::OrientCamera&) { return value(); }
};

template<>
struct DataType< ::mh_hazard::OrientCamera > {
  static const char* value()
  {
    return "mh_hazard/OrientCamera";
  }

  static const char* value(const ::mh_hazard::OrientCamera&) { return value(); }
};


// service_traits::MD5Sum< ::mh_hazard::OrientCameraRequest> should match
// service_traits::MD5Sum< ::mh_hazard::OrientCamera >
template<>
struct MD5Sum< ::mh_hazard::OrientCameraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mh_hazard::OrientCamera >::value();
  }
  static const char* value(const ::mh_hazard::OrientCameraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mh_hazard::OrientCameraRequest> should match
// service_traits::DataType< ::mh_hazard::OrientCamera >
template<>
struct DataType< ::mh_hazard::OrientCameraRequest>
{
  static const char* value()
  {
    return DataType< ::mh_hazard::OrientCamera >::value();
  }
  static const char* value(const ::mh_hazard::OrientCameraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mh_hazard::OrientCameraResponse> should match
// service_traits::MD5Sum< ::mh_hazard::OrientCamera >
template<>
struct MD5Sum< ::mh_hazard::OrientCameraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mh_hazard::OrientCamera >::value();
  }
  static const char* value(const ::mh_hazard::OrientCameraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mh_hazard::OrientCameraResponse> should match
// service_traits::DataType< ::mh_hazard::OrientCamera >
template<>
struct DataType< ::mh_hazard::OrientCameraResponse>
{
  static const char* value()
  {
    return DataType< ::mh_hazard::OrientCamera >::value();
  }
  static const char* value(const ::mh_hazard::OrientCameraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MH_HAZARD_MESSAGE_ORIENTCAMERA_H
