// Generated by gencpp from file mh_hazard/SAM.msg
// DO NOT EDIT!


#ifndef MH_HAZARD_MESSAGE_SAM_H
#define MH_HAZARD_MESSAGE_SAM_H

#include <ros/service_traits.h>


#include <mh_hazard/SAMRequest.h>
#include <mh_hazard/SAMResponse.h>


namespace mh_hazard
{

struct SAM
{

typedef SAMRequest Request;
typedef SAMResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SAM
} // namespace mh_hazard


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mh_hazard::SAM > {
  static const char* value()
  {
    return "91a25104efa47a7b7732744e46f4e2e9";
  }

  static const char* value(const ::mh_hazard::SAM&) { return value(); }
};

template<>
struct DataType< ::mh_hazard::SAM > {
  static const char* value()
  {
    return "mh_hazard/SAM";
  }

  static const char* value(const ::mh_hazard::SAM&) { return value(); }
};


// service_traits::MD5Sum< ::mh_hazard::SAMRequest> should match
// service_traits::MD5Sum< ::mh_hazard::SAM >
template<>
struct MD5Sum< ::mh_hazard::SAMRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mh_hazard::SAM >::value();
  }
  static const char* value(const ::mh_hazard::SAMRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mh_hazard::SAMRequest> should match
// service_traits::DataType< ::mh_hazard::SAM >
template<>
struct DataType< ::mh_hazard::SAMRequest>
{
  static const char* value()
  {
    return DataType< ::mh_hazard::SAM >::value();
  }
  static const char* value(const ::mh_hazard::SAMRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mh_hazard::SAMResponse> should match
// service_traits::MD5Sum< ::mh_hazard::SAM >
template<>
struct MD5Sum< ::mh_hazard::SAMResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mh_hazard::SAM >::value();
  }
  static const char* value(const ::mh_hazard::SAMResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mh_hazard::SAMResponse> should match
// service_traits::DataType< ::mh_hazard::SAM >
template<>
struct DataType< ::mh_hazard::SAMResponse>
{
  static const char* value()
  {
    return DataType< ::mh_hazard::SAM >::value();
  }
  static const char* value(const ::mh_hazard::SAMResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MH_HAZARD_MESSAGE_SAM_H
