// Generated by gencpp from file mh_hazard/Servo.msg
// DO NOT EDIT!


#ifndef MH_HAZARD_MESSAGE_SERVO_H
#define MH_HAZARD_MESSAGE_SERVO_H

#include <ros/service_traits.h>


#include <mh_hazard/ServoRequest.h>
#include <mh_hazard/ServoResponse.h>


namespace mh_hazard
{

struct Servo
{

typedef ServoRequest Request;
typedef ServoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Servo
} // namespace mh_hazard


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mh_hazard::Servo > {
  static const char* value()
  {
    return "e3a98d806e1c4fee01a17d597e27ea8e";
  }

  static const char* value(const ::mh_hazard::Servo&) { return value(); }
};

template<>
struct DataType< ::mh_hazard::Servo > {
  static const char* value()
  {
    return "mh_hazard/Servo";
  }

  static const char* value(const ::mh_hazard::Servo&) { return value(); }
};


// service_traits::MD5Sum< ::mh_hazard::ServoRequest> should match
// service_traits::MD5Sum< ::mh_hazard::Servo >
template<>
struct MD5Sum< ::mh_hazard::ServoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mh_hazard::Servo >::value();
  }
  static const char* value(const ::mh_hazard::ServoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mh_hazard::ServoRequest> should match
// service_traits::DataType< ::mh_hazard::Servo >
template<>
struct DataType< ::mh_hazard::ServoRequest>
{
  static const char* value()
  {
    return DataType< ::mh_hazard::Servo >::value();
  }
  static const char* value(const ::mh_hazard::ServoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mh_hazard::ServoResponse> should match
// service_traits::MD5Sum< ::mh_hazard::Servo >
template<>
struct MD5Sum< ::mh_hazard::ServoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mh_hazard::Servo >::value();
  }
  static const char* value(const ::mh_hazard::ServoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mh_hazard::ServoResponse> should match
// service_traits::DataType< ::mh_hazard::Servo >
template<>
struct DataType< ::mh_hazard::ServoResponse>
{
  static const char* value()
  {
    return DataType< ::mh_hazard::Servo >::value();
  }
  static const char* value(const ::mh_hazard::ServoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MH_HAZARD_MESSAGE_SERVO_H
