// Generated by gencpp from file mh_hazard/ServoRequest.msg
// DO NOT EDIT!


#ifndef MH_HAZARD_MESSAGE_SERVOREQUEST_H
#define MH_HAZARD_MESSAGE_SERVOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mh_hazard
{
template <class ContainerAllocator>
struct ServoRequest_
{
  typedef ServoRequest_<ContainerAllocator> Type;

  ServoRequest_()
    {
    }
  ServoRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::mh_hazard::ServoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mh_hazard::ServoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ServoRequest_

typedef ::mh_hazard::ServoRequest_<std::allocator<void> > ServoRequest;

typedef boost::shared_ptr< ::mh_hazard::ServoRequest > ServoRequestPtr;
typedef boost::shared_ptr< ::mh_hazard::ServoRequest const> ServoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mh_hazard::ServoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mh_hazard::ServoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace mh_hazard

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mh_hazard::ServoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mh_hazard::ServoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mh_hazard::ServoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mh_hazard::ServoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mh_hazard::ServoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mh_hazard::ServoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mh_hazard::ServoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::mh_hazard::ServoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::mh_hazard::ServoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mh_hazard/ServoRequest";
  }

  static const char* value(const ::mh_hazard::ServoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mh_hazard::ServoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::mh_hazard::ServoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mh_hazard::ServoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mh_hazard::ServoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::mh_hazard::ServoRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MH_HAZARD_MESSAGE_SERVOREQUEST_H
