// Generated by gencpp from file mh_hazard/Transcription.msg
// DO NOT EDIT!


#ifndef MH_HAZARD_MESSAGE_TRANSCRIPTION_H
#define MH_HAZARD_MESSAGE_TRANSCRIPTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mh_hazard
{
template <class ContainerAllocator>
struct Transcription_
{
  typedef Transcription_<ContainerAllocator> Type;

  Transcription_()
    : transcription()
    , audio_recieved()
    , duration(0.0)  {
    }
  Transcription_(const ContainerAllocator& _alloc)
    : transcription(_alloc)
    , audio_recieved()
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _transcription_type;
  _transcription_type transcription;

   typedef ros::Time _audio_recieved_type;
  _audio_recieved_type audio_recieved;

   typedef float _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::mh_hazard::Transcription_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mh_hazard::Transcription_<ContainerAllocator> const> ConstPtr;

}; // struct Transcription_

typedef ::mh_hazard::Transcription_<std::allocator<void> > Transcription;

typedef boost::shared_ptr< ::mh_hazard::Transcription > TranscriptionPtr;
typedef boost::shared_ptr< ::mh_hazard::Transcription const> TranscriptionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mh_hazard::Transcription_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mh_hazard::Transcription_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mh_hazard::Transcription_<ContainerAllocator1> & lhs, const ::mh_hazard::Transcription_<ContainerAllocator2> & rhs)
{
  return lhs.transcription == rhs.transcription &&
    lhs.audio_recieved == rhs.audio_recieved &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mh_hazard::Transcription_<ContainerAllocator1> & lhs, const ::mh_hazard::Transcription_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mh_hazard

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mh_hazard::Transcription_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mh_hazard::Transcription_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mh_hazard::Transcription_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mh_hazard::Transcription_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mh_hazard::Transcription_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mh_hazard::Transcription_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mh_hazard::Transcription_<ContainerAllocator> >
{
  static const char* value()
  {
    return "61ce3dbd8bc5a4089981ece3499c2e36";
  }

  static const char* value(const ::mh_hazard::Transcription_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x61ce3dbd8bc5a408ULL;
  static const uint64_t static_value2 = 0x9981ece3499c2e36ULL;
};

template<class ContainerAllocator>
struct DataType< ::mh_hazard::Transcription_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mh_hazard/Transcription";
  }

  static const char* value(const ::mh_hazard::Transcription_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mh_hazard::Transcription_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string transcription\n"
"time audio_recieved\n"
"float32 duration\n"
;
  }

  static const char* value(const ::mh_hazard::Transcription_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mh_hazard::Transcription_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.transcription);
      stream.next(m.audio_recieved);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Transcription_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mh_hazard::Transcription_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mh_hazard::Transcription_<ContainerAllocator>& v)
  {
    s << indent << "transcription: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.transcription);
    s << indent << "audio_recieved: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.audio_recieved);
    s << indent << "duration: ";
    Printer<float>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MH_HAZARD_MESSAGE_TRANSCRIPTION_H
