// Generated by gencpp from file mh_hazard/TTS.msg
// DO NOT EDIT!


#ifndef MH_HAZARD_MESSAGE_TTS_H
#define MH_HAZARD_MESSAGE_TTS_H

#include <ros/service_traits.h>


#include <mh_hazard/TTSRequest.h>
#include <mh_hazard/TTSResponse.h>


namespace mh_hazard
{

struct TTS
{

typedef TTSRequest Request;
typedef TTSResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TTS
} // namespace mh_hazard


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mh_hazard::TTS > {
  static const char* value()
  {
    return "f5c89d7cae48feffa3fe6f3e251992a4";
  }

  static const char* value(const ::mh_hazard::TTS&) { return value(); }
};

template<>
struct DataType< ::mh_hazard::TTS > {
  static const char* value()
  {
    return "mh_hazard/TTS";
  }

  static const char* value(const ::mh_hazard::TTS&) { return value(); }
};


// service_traits::MD5Sum< ::mh_hazard::TTSRequest> should match
// service_traits::MD5Sum< ::mh_hazard::TTS >
template<>
struct MD5Sum< ::mh_hazard::TTSRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mh_hazard::TTS >::value();
  }
  static const char* value(const ::mh_hazard::TTSRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mh_hazard::TTSRequest> should match
// service_traits::DataType< ::mh_hazard::TTS >
template<>
struct DataType< ::mh_hazard::TTSRequest>
{
  static const char* value()
  {
    return DataType< ::mh_hazard::TTS >::value();
  }
  static const char* value(const ::mh_hazard::TTSRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mh_hazard::TTSResponse> should match
// service_traits::MD5Sum< ::mh_hazard::TTS >
template<>
struct MD5Sum< ::mh_hazard::TTSResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mh_hazard::TTS >::value();
  }
  static const char* value(const ::mh_hazard::TTSResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mh_hazard::TTSResponse> should match
// service_traits::DataType< ::mh_hazard::TTS >
template<>
struct DataType< ::mh_hazard::TTSResponse>
{
  static const char* value()
  {
    return DataType< ::mh_hazard::TTS >::value();
  }
  static const char* value(const ::mh_hazard::TTSResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MH_HAZARD_MESSAGE_TTS_H
