// Generated by gencpp from file mh_hazard/WhisperResponse.msg
// DO NOT EDIT!


#ifndef MH_HAZARD_MESSAGE_WHISPERRESPONSE_H
#define MH_HAZARD_MESSAGE_WHISPERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mh_hazard
{
template <class ContainerAllocator>
struct WhisperResponse_
{
  typedef WhisperResponse_<ContainerAllocator> Type;

  WhisperResponse_()
    : transcription()  {
    }
  WhisperResponse_(const ContainerAllocator& _alloc)
    : transcription(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _transcription_type;
  _transcription_type transcription;





  typedef boost::shared_ptr< ::mh_hazard::WhisperResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mh_hazard::WhisperResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WhisperResponse_

typedef ::mh_hazard::WhisperResponse_<std::allocator<void> > WhisperResponse;

typedef boost::shared_ptr< ::mh_hazard::WhisperResponse > WhisperResponsePtr;
typedef boost::shared_ptr< ::mh_hazard::WhisperResponse const> WhisperResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mh_hazard::WhisperResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mh_hazard::WhisperResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mh_hazard::WhisperResponse_<ContainerAllocator1> & lhs, const ::mh_hazard::WhisperResponse_<ContainerAllocator2> & rhs)
{
  return lhs.transcription == rhs.transcription;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mh_hazard::WhisperResponse_<ContainerAllocator1> & lhs, const ::mh_hazard::WhisperResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mh_hazard

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mh_hazard::WhisperResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mh_hazard::WhisperResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mh_hazard::WhisperResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mh_hazard::WhisperResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mh_hazard::WhisperResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mh_hazard::WhisperResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mh_hazard::WhisperResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d87ceb831c5fd1ff2239ff1c5b3dfc96";
  }

  static const char* value(const ::mh_hazard::WhisperResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd87ceb831c5fd1ffULL;
  static const uint64_t static_value2 = 0x2239ff1c5b3dfc96ULL;
};

template<class ContainerAllocator>
struct DataType< ::mh_hazard::WhisperResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mh_hazard/WhisperResponse";
  }

  static const char* value(const ::mh_hazard::WhisperResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mh_hazard::WhisperResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string transcription\n"
"\n"
;
  }

  static const char* value(const ::mh_hazard::WhisperResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mh_hazard::WhisperResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.transcription);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WhisperResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mh_hazard::WhisperResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mh_hazard::WhisperResponse_<ContainerAllocator>& v)
  {
    s << indent << "transcription: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.transcription);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MH_HAZARD_MESSAGE_WHISPERRESPONSE_H
